# Generated by Django 4.0 on 2022-08-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
